### ISSUE TITLE
Homey v2

### ISSUE THREAD

**Issue by maheldt** [priknr1/com.visionsecurity#14]
Hi

Is this app ready for Homey v2.0

Best regards
MH

**Comment by michelkamp** [comment]
Same question here. On my homey v2 it fails to install at all...😒

**Comment by michelkamp** [comment]
i did a commit to fix this install issue. it is now running correctly on my home v2. the issue was the default settings that need a ID as a value . #

**Comment by LillenA4** [comment]
> i did a commit to fix this install issue. it is now running correctly on my home v2. the issue was the default settings that need a ID as a value . #

How did you do that? Is that something i can do myself. Im on Iphone.

**Comment by michelkamp** [comment]
@LillenA4 no you will have to setup a dev env and clone this repro ect.. @priknr1 any change you could have a look on this. I also have a issue that only my ZP3102 ZWAVE PLUS devices are reporting back correctly and NON zwave PLUS are only reporting once ... Any ideas ??

**Comment by michelkamp** [comment]
@priknr1 See below debug for the NON - Zwave PIR alarm trigger: 
[debug] node.CommandClass['COMMAND_CLASS_ALARM'].on('report') arguments: { '0': { token: '2e28157d-93dc-4af2-abb4-396572e6cc89' } }

And see below debug for the Zwave PLUS PIR alarm trigger:

[debug] node.CommandClass['COMMAND_CLASS_BASIC'].on('report') arguments: { '0': { token: '1b109487-7158-49b9-bb20-9a4746b9f23d' },
  '1': [Function] }
[debug] node.CommandClass['COMMAND_CLASS_NOTIFICATION'].on('report') arguments: { '0': { token: '1b109487-7158-49b9-bb20-9a4746b9f23d' },
  '1': [Function] }

So it looks like something is not reported. Could this be a Homey v2 firmware issue ?? any hint on this ??

**Comment by priknr1** [comment]
I added the changes that @michelkamp made into a new version.
It should be available in the appstore soon.

Please let me know if the installation on Homey 2.0 works after the update.


@michelkamp   I am not much of a programmer,  the apps I have made so far, are all copy/past/steal work.
Any chance you can dive into this yourself?
Would you be so kind to make a new issue for this, since I will close this topic if the app will install now in 2.0
